---

- name: Configuring Apache Server
  hosts: all
  tasks:
  - name: Installation of Apache server package
    yum:
     name: httpd
     state: present

  - name: Create Index File
    copy:
     content: "Hello Fidelity!! This is Ansible Automation Here!! {{ name }}"
     dest: /var/www/html/index.html

  - name: Starting  The Service
    service:
     name: httpd
     state: started
     enabled: yes
  - name: Printing the webpage
    uri: 
     url:  "{{ myurl }}"  
     return_content: yes
    register: url

  - name: debug module
    debug:
     var: url.content 


